version: '3'
services:
  dns:
    image: cloudgenius/cloudflare-ddns:latest
    environment:
      - CF_HOST=cloudgenius.co
      - CF_API_KEY=926e93ebd56638754af6ab32b39fff42e7e89
      - CF_API_EMAIL=nilesh@cloudgeni.us
#      - CF_HOST=${DOMAIN}
#      - CF_API_KEY=${KEY}
#      - CF_API_EMAIL=${MAIL}
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloudgenius.co"]
      interval: 20s
      timeout: 10s
      retries: 3
